<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="3" failed="1" ignored="0" total="4" passed="0">
  <reporter-output>
    <line>
      <![CDATA[====db connection successful====]]>
    </line>
    <line>
      <![CDATA[====browser launch successful====]]>
    </line>
    <line>
      <![CDATA[====login successfull====]]>
    </line>
    <line>
      <![CDATA[====logout successfull====]]>
    </line>
    <line>
      <![CDATA[====login successfull====]]>
    </line>
    <line>
      <![CDATA[====logout successfull====]]>
    </line>
    <line>
      <![CDATA[====login successfull====]]>
    </line>
    <line>
      <![CDATA[====logout successfull====]]>
    </line>
    <line>
      <![CDATA[====login successfull====]]>
    </line>
    <line>
      <![CDATA[====logout successfull====]]>
    </line>
    <line>
      <![CDATA[====browser close successfull====]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="379350" started-at="2022-03-16T11:45:44Z" finished-at="2022-03-16T11:52:03Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="379350" started-at="2022-03-16T11:45:44Z" finished-at="2022-03-16T11:52:03Z">
      <class name="com.crm.OrganizationTests.CreateOrganizationTestNGTest">
        <test-method status="PASS" signature="connectionDataBase()[pri:0, instance:com.crm.OrganizationTests.CreateOrganizationTestNGTest@6fd02e5]" name="connectionDataBase" is-config="true" duration-ms="63" started-at="2022-03-16T11:45:44Z" finished-at="2022-03-16T11:45:44Z">
          <reporter-output>
            <line>
              <![CDATA[====db connection successful====]]>
            </line>
          </reporter-output>
        </test-method> <!-- connectionDataBase -->
        <test-method status="PASS" signature="launchTheBrowser()[pri:0, instance:com.crm.OrganizationTests.CreateOrganizationTestNGTest@6fd02e5]" name="launchTheBrowser" is-config="true" duration-ms="116984" started-at="2022-03-16T11:45:45Z" finished-at="2022-03-16T11:47:42Z">
          <reporter-output>
            <line>
              <![CDATA[====browser launch successful====]]>
            </line>
          </reporter-output>
        </test-method> <!-- launchTheBrowser -->
        <test-method status="PASS" signature="login()[pri:0, instance:com.crm.OrganizationTests.CreateOrganizationTestNGTest@6fd02e5]" name="login" is-config="true" duration-ms="81970" started-at="2022-03-16T11:47:42Z" finished-at="2022-03-16T11:49:04Z">
          <reporter-output>
            <line>
              <![CDATA[====login successfull====]]>
            </line>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="SKIP" signature="createorganizationTestNGTest()[pri:0, instance:com.crm.OrganizationTests.CreateOrganizationTestNGTest@6fd02e5]" name="createorganizationTestNGTest" duration-ms="65043" started-at="2022-03-16T11:49:04Z" finished-at="2022-03-16T11:50:09Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at com.crm.OrganizationTests.CreateOrganizationTestNGTest.createorganizationTestNGTest(CreateOrganizationTestNGTest.java:25)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createorganizationTestNGTest -->
        <test-method status="PASS" signature="logout()[pri:0, instance:com.crm.OrganizationTests.CreateOrganizationTestNGTest@6fd02e5]" name="logout" is-config="true" duration-ms="11362" started-at="2022-03-16T11:50:09Z" finished-at="2022-03-16T11:50:20Z">
          <reporter-output>
            <line>
              <![CDATA[====logout successfull====]]>
            </line>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method status="PASS" signature="login()[pri:0, instance:com.crm.OrganizationTests.CreateOrganizationTestNGTest@6fd02e5]" name="login" is-config="true" duration-ms="7210" started-at="2022-03-16T11:50:20Z" finished-at="2022-03-16T11:50:28Z">
          <reporter-output>
            <line>
              <![CDATA[====login successfull====]]>
            </line>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="SKIP" signature="createorganizationTestNGTest()[pri:0, instance:com.crm.OrganizationTests.CreateOrganizationTestNGTest@6fd02e5]" name="createorganizationTestNGTest" duration-ms="16688" started-at="2022-03-16T11:50:28Z" finished-at="2022-03-16T11:50:44Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at com.crm.OrganizationTests.CreateOrganizationTestNGTest.createorganizationTestNGTest(CreateOrganizationTestNGTest.java:25)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createorganizationTestNGTest -->
        <test-method status="PASS" signature="logout()[pri:0, instance:com.crm.OrganizationTests.CreateOrganizationTestNGTest@6fd02e5]" name="logout" is-config="true" duration-ms="4379" started-at="2022-03-16T11:50:44Z" finished-at="2022-03-16T11:50:49Z">
          <reporter-output>
            <line>
              <![CDATA[====logout successfull====]]>
            </line>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method status="PASS" signature="login()[pri:0, instance:com.crm.OrganizationTests.CreateOrganizationTestNGTest@6fd02e5]" name="login" is-config="true" duration-ms="7201" started-at="2022-03-16T11:50:49Z" finished-at="2022-03-16T11:50:56Z">
          <reporter-output>
            <line>
              <![CDATA[====login successfull====]]>
            </line>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="SKIP" signature="createorganizationTestNGTest()[pri:0, instance:com.crm.OrganizationTests.CreateOrganizationTestNGTest@6fd02e5]" name="createorganizationTestNGTest" duration-ms="19076" started-at="2022-03-16T11:50:56Z" finished-at="2022-03-16T11:51:15Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at com.crm.OrganizationTests.CreateOrganizationTestNGTest.createorganizationTestNGTest(CreateOrganizationTestNGTest.java:25)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createorganizationTestNGTest -->
        <test-method status="PASS" signature="logout()[pri:0, instance:com.crm.OrganizationTests.CreateOrganizationTestNGTest@6fd02e5]" name="logout" is-config="true" duration-ms="6182" started-at="2022-03-16T11:51:15Z" finished-at="2022-03-16T11:51:21Z">
          <reporter-output>
            <line>
              <![CDATA[====logout successfull====]]>
            </line>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method status="PASS" signature="login()[pri:0, instance:com.crm.OrganizationTests.CreateOrganizationTestNGTest@6fd02e5]" name="login" is-config="true" duration-ms="8756" started-at="2022-03-16T11:51:21Z" finished-at="2022-03-16T11:51:30Z">
          <reporter-output>
            <line>
              <![CDATA[====login successfull====]]>
            </line>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="FAIL" signature="createorganizationTestNGTest()[pri:0, instance:com.crm.OrganizationTests.CreateOrganizationTestNGTest@6fd02e5]" name="createorganizationTestNGTest" duration-ms="23102" started-at="2022-03-16T11:51:30Z" finished-at="2022-03-16T11:51:53Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at com.crm.OrganizationTests.CreateOrganizationTestNGTest.createorganizationTestNGTest(CreateOrganizationTestNGTest.java:25)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createorganizationTestNGTest -->
        <test-method status="PASS" signature="logout()[pri:0, instance:com.crm.OrganizationTests.CreateOrganizationTestNGTest@6fd02e5]" name="logout" is-config="true" duration-ms="4472" started-at="2022-03-16T11:51:55Z" finished-at="2022-03-16T11:51:59Z">
          <reporter-output>
            <line>
              <![CDATA[====logout successfull====]]>
            </line>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:com.crm.OrganizationTests.CreateOrganizationTestNGTest@6fd02e5]" name="closeBrowser" is-config="true" duration-ms="3820" started-at="2022-03-16T11:51:59Z" finished-at="2022-03-16T11:52:03Z">
          <reporter-output>
            <line>
              <![CDATA[====browser close successfull====]]>
            </line>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method status="FAIL" signature="closeDb()[pri:0, instance:com.crm.OrganizationTests.CreateOrganizationTestNGTest@6fd02e5]" name="closeDb" is-config="true" duration-ms="93" started-at="2022-03-16T11:52:06Z" finished-at="2022-03-16T11:52:06Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.crm.GenericLibrary.DatabaseUtility.closeDB(DatabaseUtility.java:34)
at com.crm.GenericLibrary.BaseClass.closeDb(BaseClass.java:103)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:425)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDb -->
      </class> <!-- com.crm.OrganizationTests.CreateOrganizationTestNGTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
